### ISSUE TITLE
unit 2 lesson 6 activity 1

### ISSUE THREAD

**Issue by instinct164** [ricky8k/APCSA-ProjectStem#2]
unit 2 lesson 6, activity one doesn’t work, doesn’t pass test 1 and 3
![IMG_0781](https://github.com/ricky8k/APCSA-ProjectStem/assets/145602769/f50148ef-2fe9-495b-aa9a-2677e3ee85fa)

**Comment by ricky8k** [comment]
There is no underlying issue with the original code. As such, this issue won't be fixed.

Please note that the sample source code is intended to work for the 2022-23 AP CS A curriculum. I do not have access to newer lessons. These solutions may grow out-of-date as Project Stem changes exercises each year.
